version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongo://mongo/beerjs
    networks:
      - beerjs
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - .:/usr/src/app

  mongo:
    image: mvertes/alpine-mongo:3.4.4-0
    networks:
      - beerjs
    volumes:
      - mongo:/data/db

volumes:
  mongo:

networks:
  beerjs:
