version: '3'

services:
  app:
    build: .
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongo://mongo/beerjs
    networks:
      - beerjs
    ports:
      - "3000:3000"

  mongo:
    image: mvertes/alpine-mongo:3.6.4-0@sha256:245799dcfdb1bcdb42e8f97da8a6d147a249b8e7f1dd00cc729a7dfe7d0e4452
    networks:
      - beerjs
    volumes:
      - mongo:/data/db

volumes:
  mongo:

networks:
  beerjs:
