version: '3'

services:
  app:
    build: .
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongo://mongo/beerjs
    networks:
      - beerjs
    ports:
      - "3000:3000"

  mongo:
    image: mvertes/alpine-mongo:3.4.4-0@sha256:472c285e9b50becea83f20e930a0897d5b1e53bd3970e8c9b498ddd64a6e0a16
    networks:
      - beerjs
    volumes:
      - mongo:/data/db

volumes:
  mongo:

networks:
  beerjs:
