version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongo://mongo/beerjs
    networks:
      - beerjs
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - .:/usr/src/app

  mongo:
    image: mvertes/alpine-mongo:3.6.3-0@sha256:3fb2675c7e6e4cfb93bdc4a7326ebabd536786ec4723d6348f2b7ad70bff36ab
    networks:
      - beerjs
    volumes:
      - mongo:/data/db

volumes:
  mongo:

networks:
  beerjs:
