version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongo://mongo/beerjs
    networks:
      - beerjs
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - .:/usr/src/app

  mongo:
    image: mvertes/alpine-mongo:3.6.5-0@sha256:16095d82e1c5ba24943c432431d1c74c383620a6ac09abaa99b716e2dbb5e283
    networks:
      - beerjs
    volumes:
      - mongo:/data/db

volumes:
  mongo:

networks:
  beerjs:
